# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

name: Docker build and push

on:
  push:
    branches:
      - staging

env:
  REGISTRY_NAME: ataacr

jobs:
  build-and-deploy:
    name: Docker Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=${{ env.REGISTRY_NAME }}.azurecr.io/chainbridge
          TAGS="${DOCKER_IMAGE}:staging-${{ github.sha }}"
          echo ::set-output name=tags::${TAGS}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.ATA_ACR_USERNAME }}
          password: ${{ secrets.ATA_ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ steps.prep.outputs.tags }}
          docker push ${{ steps.prep.outputs.tags }}
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.prep.outputs.tags }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
